In [1]:
import numpy as np

In [2]:
#Let's sstart by initializing an array. For example a 1D array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
#This is a 2D array
b = np.array([[9.0,3.2,1.0],[2.0,4.0,7.2]])
b

array([[9. , 3.2, 1. ],
       [2. , 4. , 7.2]])

In [8]:
#We can check what type of dimension the array is using the code;
a.ndim

1

In [9]:
b.ndim

2

In [10]:
#Let's get the shape of each array
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [12]:
#Additionally, we can check the type
a.dtype

dtype('int32')

In [13]:
b.dtype

dtype('float64')

In [15]:
#Random decimal number
np.random.rand(4,2)

array([[0.89597451, 0.92184866],
       [0.92998799, 0.25356999],
       [0.54187474, 0.39925587],
       [0.85072152, 0.22878546]])

In [16]:
np.full_like(a,4)

array([4, 4, 4])

In [17]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])