In [28]:
import numpy as np
from sklearn.datasets import load_wine
a = [1,2,3,4,5,6,7,8,9,0]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [35]:
arr = [[1, 2, 3]]
arr
arr * 10

[[1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3]]

In [30]:
#We'll start by importing a dataset from sklearn and use one of its columns/labels to learn numpy
df = load_wine()
df

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [31]:
df['data'] 

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [32]:
wine_array = df['data']
wine_array

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [33]:
alcohol = wine_array[:, 0]
alcohol

array([14.23, 13.2 , 13.16, 14.37, 13.24, 14.2 , 14.39, 14.06, 14.83,
       13.86, 14.1 , 14.12, 13.75, 14.75, 14.38, 13.63, 14.3 , 13.83,
       14.19, 13.64, 14.06, 12.93, 13.71, 12.85, 13.5 , 13.05, 13.39,
       13.3 , 13.87, 14.02, 13.73, 13.58, 13.68, 13.76, 13.51, 13.48,
       13.28, 13.05, 13.07, 14.22, 13.56, 13.41, 13.88, 13.24, 13.05,
       14.21, 14.38, 13.9 , 14.1 , 13.94, 13.05, 13.83, 13.82, 13.77,
       13.74, 13.56, 14.22, 13.29, 13.72, 12.37, 12.33, 12.64, 13.67,
       12.37, 12.17, 12.37, 13.11, 12.37, 13.34, 12.21, 12.29, 13.86,
       13.49, 12.99, 11.96, 11.66, 13.03, 11.84, 12.33, 12.7 , 12.  ,
       12.72, 12.08, 13.05, 11.84, 12.67, 12.16, 11.65, 11.64, 12.08,
       12.08, 12.  , 12.69, 12.29, 11.62, 12.47, 11.81, 12.29, 12.37,
       12.29, 12.08, 12.6 , 12.34, 11.82, 12.51, 12.42, 12.25, 12.72,
       12.22, 11.61, 11.46, 12.52, 11.76, 11.41, 12.08, 11.03, 11.82,
       12.42, 12.77, 12.  , 11.45, 11.56, 12.42, 13.05, 11.87, 12.07,
       12.43, 11.79,

In [34]:
#Mean
np.mean(alcohol)

13.00061797752809

In [36]:
#Square 
np.square(arr)

array([[1, 4, 9]], dtype=int32)

In [37]:
#Minimum
np.min(alcohol)

11.03

In [39]:
#Maximum
np.max(alcohol)

14.83

In [40]:
#Standard Deviation
np.std(alcohol)

0.8095429145285168

In [41]:
#Filtering using boolean masks
alcohol_under_13_boolean_mask = alcohol < 13

In [43]:
wine_array[alcohol_under_13_boolean_mask]

array([[1.293e+01, 3.800e+00, 2.650e+00, ..., 1.030e+00, 3.520e+00,
        7.700e+02],
       [1.285e+01, 1.600e+00, 2.520e+00, ..., 1.090e+00, 3.630e+00,
        1.015e+03],
       [1.237e+01, 9.400e-01, 1.360e+00, ..., 1.050e+00, 1.820e+00,
        5.200e+02],
       ...,
       [1.282e+01, 3.370e+00, 2.300e+00, ..., 7.200e-01, 1.750e+00,
        6.850e+02],
       [1.220e+01, 3.030e+00, 2.320e+00, ..., 6.600e-01, 1.830e+00,
        5.100e+02],
       [1.277e+01, 2.390e+00, 2.280e+00, ..., 5.700e-01, 1.630e+00,
        4.700e+02]])

In [44]:
wine_array[alcohol_under_13_boolean_mask].shape

(86, 13)

In [47]:
magnesium = wine_array[:, 4]
magnesium_over_120_boolean_mask = magnesium > 120
magnesium_over_120_boolean_mask

array([ True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [48]:
combined_mask = alcohol_under_13_boolean_mask & magnesium_over_120_boolean_mask

In [51]:
wine_array[combined_mask][:, (0,4)]

array([[ 12.21, 151.  ],
       [ 12.99, 139.  ],
       [ 12.33, 136.  ],
       [ 12.47, 162.  ],
       [ 11.81, 134.  ],
       [ 12.86, 122.  ]])

In [52]:
wine_array[
    (alcohol < 13) &
    (magnesium > 120)
]

array([[1.221e+01, 1.190e+00, 1.750e+00, 1.680e+01, 1.510e+02, 1.850e+00,
        1.280e+00, 1.400e-01, 2.500e+00, 2.850e+00, 1.280e+00, 3.070e+00,
        7.180e+02],
       [1.299e+01, 1.670e+00, 2.600e+00, 3.000e+01, 1.390e+02, 3.300e+00,
        2.890e+00, 2.100e-01, 1.960e+00, 3.350e+00, 1.310e+00, 3.500e+00,
        9.850e+02],
       [1.233e+01, 9.900e-01, 1.950e+00, 1.480e+01, 1.360e+02, 1.900e+00,
        1.850e+00, 3.500e-01, 2.760e+00, 3.400e+00, 1.060e+00, 2.310e+00,
        7.500e+02],
       [1.247e+01, 1.520e+00, 2.200e+00, 1.900e+01, 1.620e+02, 2.500e+00,
        2.270e+00, 3.200e-01, 3.280e+00, 2.600e+00, 1.160e+00, 2.630e+00,
        9.370e+02],
       [1.181e+01, 2.120e+00, 2.740e+00, 2.150e+01, 1.340e+02, 1.600e+00,
        9.900e-01, 1.400e-01, 1.560e+00, 2.500e+00, 9.500e-01, 2.260e+00,
        6.250e+02],
       [1.286e+01, 1.350e+00, 2.320e+00, 1.800e+01, 1.220e+02, 1.510e+00,
        1.250e+00, 2.100e-01, 9.400e-01, 4.100e+00, 7.600e-01, 1.290e+00,
        6.30

# If..then content


In [53]:
alcohol

array([14.23, 13.2 , 13.16, 14.37, 13.24, 14.2 , 14.39, 14.06, 14.83,
       13.86, 14.1 , 14.12, 13.75, 14.75, 14.38, 13.63, 14.3 , 13.83,
       14.19, 13.64, 14.06, 12.93, 13.71, 12.85, 13.5 , 13.05, 13.39,
       13.3 , 13.87, 14.02, 13.73, 13.58, 13.68, 13.76, 13.51, 13.48,
       13.28, 13.05, 13.07, 14.22, 13.56, 13.41, 13.88, 13.24, 13.05,
       14.21, 14.38, 13.9 , 14.1 , 13.94, 13.05, 13.83, 13.82, 13.77,
       13.74, 13.56, 14.22, 13.29, 13.72, 12.37, 12.33, 12.64, 13.67,
       12.37, 12.17, 12.37, 13.11, 12.37, 13.34, 12.21, 12.29, 13.86,
       13.49, 12.99, 11.96, 11.66, 13.03, 11.84, 12.33, 12.7 , 12.  ,
       12.72, 12.08, 13.05, 11.84, 12.67, 12.16, 11.65, 11.64, 12.08,
       12.08, 12.  , 12.69, 12.29, 11.62, 12.47, 11.81, 12.29, 12.37,
       12.29, 12.08, 12.6 , 12.34, 11.82, 12.51, 12.42, 12.25, 12.72,
       12.22, 11.61, 11.46, 12.52, 11.76, 11.41, 12.08, 11.03, 11.82,
       12.42, 12.77, 12.  , 11.45, 11.56, 12.42, 13.05, 11.87, 12.07,
       12.43, 11.79,

In [55]:
np.where(alcohol > 12, "low alcohol" , "other")

array(['low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcohol',
       'low alcohol', 'low alcohol', 'low alcohol', 'low alcoh

In [56]:
np.sort(alcohol)

array([11.03, 11.41, 11.45, 11.46, 11.56, 11.61, 11.62, 11.64, 11.65,
       11.66, 11.76, 11.79, 11.81, 11.82, 11.82, 11.84, 11.84, 11.87,
       11.96, 12.  , 12.  , 12.  , 12.04, 12.07, 12.08, 12.08, 12.08,
       12.08, 12.08, 12.16, 12.17, 12.2 , 12.21, 12.22, 12.25, 12.25,
       12.25, 12.29, 12.29, 12.29, 12.29, 12.33, 12.33, 12.34, 12.36,
       12.37, 12.37, 12.37, 12.37, 12.37, 12.37, 12.42, 12.42, 12.42,
       12.43, 12.45, 12.47, 12.51, 12.51, 12.52, 12.53, 12.58, 12.6 ,
       12.6 , 12.64, 12.67, 12.69, 12.7 , 12.7 , 12.72, 12.72, 12.77,
       12.77, 12.79, 12.81, 12.82, 12.84, 12.85, 12.85, 12.86, 12.87,
       12.88, 12.93, 12.93, 12.96, 12.99, 13.03, 13.05, 13.05, 13.05,
       13.05, 13.05, 13.05, 13.07, 13.08, 13.11, 13.11, 13.16, 13.16,
       13.17, 13.17, 13.2 , 13.23, 13.24, 13.24, 13.27, 13.28, 13.29,
       13.3 , 13.32, 13.34, 13.36, 13.39, 13.4 , 13.4 , 13.41, 13.45,
       13.48, 13.48, 13.49, 13.49, 13.5 , 13.5 , 13.51, 13.52, 13.56,
       13.56, 13.58,

In [61]:
#Sorts using indexes
np.argsort(alcohol)

array([115, 113, 120, 110, 121, 109,  94,  88,  87,  75, 112, 127,  96,
       103, 116,  84,  77, 124,  74, 119,  91,  80, 129, 125,  82, 114,
        89,  90, 100,  86,  64, 170,  69, 108, 144, 136, 106,  97,  70,
        93,  99,  60,  78, 102, 160,  67,  65,  63,  98, 128,  59, 105,
       122, 117, 126, 157,  95, 104, 134, 111, 137, 154, 135, 101,  61,
        85,  92,  79, 133, 107,  81, 171, 118, 151, 132, 167, 139,  23,
       162, 130, 147, 131,  21, 140, 163,  73,  76, 123,  44,  25,  83,
        37,  50,  38, 149,  66, 152, 145,   2, 176, 155,   1, 153,   4,
        43, 175,  36,  57,  27, 148,  68, 141,  26, 174, 169,  41, 166,
       159,  35, 138,  72, 150,  24,  34, 142,  55,  40,  31, 168, 143,
        15,  19,  62,  32, 161,  22, 173,  58,  30, 165,  54,  12,  33,
        53, 164,  52,  51,  17, 156,  71,   9,  28,  42, 146,  47,  49,
        29,  20,   7,  48,  10,  11, 177, 172,  18,   5,  45,  56,  39,
         0,  16, 158,   3,  46,  14,   6,  13,   8], dtype=int64